# PostgreSQL local — perfil para desarrollo con Docker Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5433/football_db
spring.datasource.username=football_user
spring.datasource.password=football_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Assets path (relativo al directorio de ejecucion)
assets.base-path=data/assets

# Logging
logging.file.name=data/logs/football-app.log
logging.level.com.football.boardgame=DEBUG

backup.cloud.enabled=true
google.drive.folder.id=1kfWO8fEzmHARlLgnc6eIzLaUblEmrA1N
google.credentials.path=classpath:config/google/credentials.json
